import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, String, Text
from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


class Post(Base):
    __tablename__ = "posts"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    thread_id = Column(String, nullable=False)  # linked to the LangGraph's checkpointer
    user_input = Column(Text, nullable=False)
    post_text = Column(Text, nullable=True)  # generated by Writer's node
    image_url = Column(Text, nullable=True)  # generated by Diagrammer's node
    created_at = Column(DateTime, default=lambda: datetime.now(timezone.utc))
